language: node_js
git:
  depth: 10
node_js:
  - "0.10"
install:
  - npm install -g grunt-cli
  - npm install
before_script: grunt build
env:
  global:
    - SAUCE_USERNAME: fallback
    - secure: rz2hQG/IyRJUM7wPMtE5KfIru/kk2bUd8jPovwSR1JF7mtVRYRmgdmFDeMRqETWXfFUGmQ/q+5jU0YxXynJCjWTkyv8uK44Aj7ZhAR0TwwvSi5+oXlY8l5QeNTabLLqnKkK2isJCRnoGJeYiAJxuHBwN59IRPWwmPJs0hcMPy2Q=
    - secure: WZfc/XmC6Ha4QQWaE4sLBWwtpjvmeaFtF3/XzjvbzpcJje7rdpphCYGNxYePC0hf0AScf5aCkUmy68gYHiBDUTtILbfDQrPSXBk4ZMQ/pMOScH4oC176y2Ygy6spC4+KmT4o1qeHFg8yr7JWDw8k0waobJ4zAX1LVllDAjovimQ=
